### ISSUE TITLE
Не качает

### ISSUE THREAD

**Issue by Flashwalker** [kettle017/RU_Bookmate_downloader#3]
```
$ venv/bin/python3 -m pip install httpx[http2] pillow pywebview pywebview[qt] pywebview[gtk] reportlab ebooklib BeautifulSoup4
```

Не качает

```
$ venv/bin/python3 RUBookmatedownloader.py --maxbitrate True --audiobooks JdVG0Ufi

File downloaded successfully to mybooks/audiobooks/ ... .jpeg
File downloaded successfully to mybooks/audiobooks/ ... .json

Traceback (most recent call last):
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 254, in __aiter__
    async for part in self._httpcore_stream:
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
    raise exc
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/RU_Bookmate_downloader.git/RUBookmatedownloader.py", line 274, in <module>
    download_audio_book(args.audiobooks,"")
  File "/home/user/RU_Bookmate_downloader.git/RUBookmatedownloader.py", line 242, in download_audio_book
    asyncio.run(download_file(download_urls[download_url],f'{download_dir}Глава_{download_url+1}.m4a'))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/RU_Bookmate_downloader.git/RUBookmatedownloader.py", line 84, in download_file
    response = await client.get(url,headers=headers,timeout=None)
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_client.py", line 1675, in send
    raise exc
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_client.py", line 1669, in send
    await response.aread()
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_models.py", line 911, in aread
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_models.py", line 911, in <listcomp>
    self._content = b"".join([part async for part in self.aiter_bytes()])
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_models.py", line 929, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_models.py", line 987, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_client.py", line 149, in __aiter__
    async for chunk in self._stream:
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 253, in __aiter__
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/RU_Bookmate_downloader.git/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadError

```

**Comment by asaldele1** [comment]
Скажите, пожалуйста, проблема всё ещё актуальна? Пока закрываю.
